### Create Cart
POST http://localhost:3000/api/cart
Content-Type: application/json

{
  "userId": "6e1c8907-ca9e-4d2c-930e-5fb1243d07f3",
  "storeId": "b6408d37-96a8-4cf1-8bd6-2599f6c87485",
  "items": [
    {
      "productId": "171bf19c-70b9-4a43-8a47-78270ecebbf1",
      "quantity": 2
    }
  ]
}

### Get Cart by ID
GET http://localhost:3000/api/cart/0578ccd8-e4f2-4bef-ba1d-eb529ec8bd4c

### Get by User ID
GET http://localhost:3000/api/cart/user/6e1c8907-ca9e-4d2c-930e-5fb1243d07f3

### Add Cart Item
POST http://localhost:3000/api/cart/c3a4969a-0417-428c-bb31-3535dcda5f8f/item
Content-Type: application/json

{
  "userId": "6e1c8907-ca9e-4d2c-930e-5fb1243d07f3",
  "productId": "23b8f600-e313-4a80-8096-12ef68543ee6",
  "quantity": 2
}

### Change Cart Item Quantity
PATCH http://localhost:3000/api/cart/c3a4969a-0417-428c-bb31-3535dcda5f8f/item/419ebeb4-0dfd-4b68-aa40-03186439a2a5
Content-Type: application/json

{
  "userId": "6e1c8907-ca9e-4d2c-930e-5fb1243d07f3",
  "quantity": 5
}