### Criar uma nova sessão de chat
POST http://localhost:3000/api/chat
Content-Type: application/json

{
  "userId": "59e95b91-3b1d-4042-a1fd-c77b88369fba"
}

### Buscar uma sessão de chat por ID e userId
GET http://localhost:3000/api/chat/28901115-984f-4648-98aa-26222040bc11

### Enviar uma mensagem para a sessão de chat
POST http://localhost:3000/api/chat/28901115-984f-4648-98aa-26222040bc11/message
Content-Type: application/json

{
  "message": "o que preciso para fazer um bolo de chocolate?",
  "userId": "59e95b91-3b1d-4042-a1fd-c77b88369fba"
}